package com.ferronica.app.domain;

import static com.ferronica.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ArticuloAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticuloAllPropertiesEquals(Articulo expected, Articulo actual) {
        assertArticuloAutoGeneratedPropertiesEquals(expected, actual);
        assertArticuloAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticuloAllUpdatablePropertiesEquals(Articulo expected, Articulo actual) {
        assertArticuloUpdatableFieldsEquals(expected, actual);
        assertArticuloUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticuloAutoGeneratedPropertiesEquals(Articulo expected, Articulo actual) {
        assertThat(actual)
            .as("Verify Articulo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticuloUpdatableFieldsEquals(Articulo expected, Articulo actual) {
        assertThat(actual)
            .as("Verify Articulo relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a ->
                assertThat(a.getExistencia())
                    .as("check existencia")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getExistencia())
            )
            .satisfies(a ->
                assertThat(a.getExistenciaMinima())
                    .as("check existenciaMinima")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getExistenciaMinima())
            )
            .satisfies(a ->
                assertThat(a.getPrecio()).as("check precio").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrecio())
            )
            .satisfies(a -> assertThat(a.getCosto()).as("check costo").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCosto()))
            .satisfies(a -> assertThat(a.getImagen()).as("check imagen").isEqualTo(expected.getImagen()))
            .satisfies(a -> assertThat(a.getImagenContentType()).as("check imagen contenty type").isEqualTo(expected.getImagenContentType())
            )
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticuloUpdatableRelationshipsEquals(Articulo expected, Articulo actual) {
        assertThat(actual)
            .as("Verify Articulo relationships")
            .satisfies(a -> assertThat(a.getCategoria()).as("check categoria").isEqualTo(expected.getCategoria()))
            .satisfies(a -> assertThat(a.getUnidadMedida()).as("check unidadMedida").isEqualTo(expected.getUnidadMedida()));
    }
}
