package com.ferronica.app.domain;

import static com.ferronica.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DetalleIngresoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleIngresoAllPropertiesEquals(DetalleIngreso expected, DetalleIngreso actual) {
        assertDetalleIngresoAutoGeneratedPropertiesEquals(expected, actual);
        assertDetalleIngresoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleIngresoAllUpdatablePropertiesEquals(DetalleIngreso expected, DetalleIngreso actual) {
        assertDetalleIngresoUpdatableFieldsEquals(expected, actual);
        assertDetalleIngresoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleIngresoAutoGeneratedPropertiesEquals(DetalleIngreso expected, DetalleIngreso actual) {
        assertThat(actual)
            .as("Verify DetalleIngreso auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleIngresoUpdatableFieldsEquals(DetalleIngreso expected, DetalleIngreso actual) {
        assertThat(actual)
            .as("Verify DetalleIngreso relevant properties")
            .satisfies(a ->
                assertThat(a.getCantidad()).as("check cantidad").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCantidad())
            )
            .satisfies(a ->
                assertThat(a.getCostoUnitario())
                    .as("check costoUnitario")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCostoUnitario())
            )
            .satisfies(a -> assertThat(a.getMonto()).as("check monto").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMonto()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleIngresoUpdatableRelationshipsEquals(DetalleIngreso expected, DetalleIngreso actual) {
        assertThat(actual)
            .as("Verify DetalleIngreso relationships")
            .satisfies(a -> assertThat(a.getArticulo()).as("check articulo").isEqualTo(expected.getArticulo()))
            .satisfies(a -> assertThat(a.getIngreso()).as("check ingreso").isEqualTo(expected.getIngreso()));
    }
}
