package com.ferronica.app.domain;

import static com.ferronica.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DetalleVentaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleVentaAllPropertiesEquals(DetalleVenta expected, DetalleVenta actual) {
        assertDetalleVentaAutoGeneratedPropertiesEquals(expected, actual);
        assertDetalleVentaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleVentaAllUpdatablePropertiesEquals(DetalleVenta expected, DetalleVenta actual) {
        assertDetalleVentaUpdatableFieldsEquals(expected, actual);
        assertDetalleVentaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleVentaAutoGeneratedPropertiesEquals(DetalleVenta expected, DetalleVenta actual) {
        assertThat(actual)
            .as("Verify DetalleVenta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleVentaUpdatableFieldsEquals(DetalleVenta expected, DetalleVenta actual) {
        assertThat(actual)
            .as("Verify DetalleVenta relevant properties")
            .satisfies(a ->
                assertThat(a.getCantidad()).as("check cantidad").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCantidad())
            )
            .satisfies(a ->
                assertThat(a.getPrecioVenta())
                    .as("check precioVenta")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioVenta())
            )
            .satisfies(a ->
                assertThat(a.getDescuento()).as("check descuento").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getDescuento())
            )
            .satisfies(a -> assertThat(a.getMonto()).as("check monto").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMonto()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleVentaUpdatableRelationshipsEquals(DetalleVenta expected, DetalleVenta actual) {
        assertThat(actual)
            .as("Verify DetalleVenta relationships")
            .satisfies(a -> assertThat(a.getArticulo()).as("check articulo").isEqualTo(expected.getArticulo()))
            .satisfies(a -> assertThat(a.getVenta()).as("check venta").isEqualTo(expected.getVenta()));
    }
}
