package com.ferronica.app.domain;

import static com.ferronica.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DevolucionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDevolucionAllPropertiesEquals(Devolucion expected, Devolucion actual) {
        assertDevolucionAutoGeneratedPropertiesEquals(expected, actual);
        assertDevolucionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDevolucionAllUpdatablePropertiesEquals(Devolucion expected, Devolucion actual) {
        assertDevolucionUpdatableFieldsEquals(expected, actual);
        assertDevolucionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDevolucionAutoGeneratedPropertiesEquals(Devolucion expected, Devolucion actual) {
        assertThat(actual)
            .as("Verify Devolucion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDevolucionUpdatableFieldsEquals(Devolucion expected, Devolucion actual) {
        assertThat(actual)
            .as("Verify Devolucion relevant properties")
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
            .satisfies(a -> assertThat(a.getMotivo()).as("check motivo").isEqualTo(expected.getMotivo()))
            .satisfies(a -> assertThat(a.getTotal()).as("check total").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDevolucionUpdatableRelationshipsEquals(Devolucion expected, Devolucion actual) {
        assertThat(actual)
            .as("Verify Devolucion relationships")
            .satisfies(a -> assertThat(a.getVenta()).as("check venta").isEqualTo(expected.getVenta()));
    }
}
