package com.ferronica.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmpresaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpresaAllPropertiesEquals(Empresa expected, Empresa actual) {
        assertEmpresaAutoGeneratedPropertiesEquals(expected, actual);
        assertEmpresaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpresaAllUpdatablePropertiesEquals(Empresa expected, Empresa actual) {
        assertEmpresaUpdatableFieldsEquals(expected, actual);
        assertEmpresaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpresaAutoGeneratedPropertiesEquals(Empresa expected, Empresa actual) {
        assertThat(actual)
            .as("Verify Empresa auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpresaUpdatableFieldsEquals(Empresa expected, Empresa actual) {
        assertThat(actual)
            .as("Verify Empresa relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getRuc()).as("check ruc").isEqualTo(expected.getRuc()))
            .satisfies(a -> assertThat(a.getRegimenFiscal()).as("check regimenFiscal").isEqualTo(expected.getRegimenFiscal()))
            .satisfies(a -> assertThat(a.getDireccion()).as("check direccion").isEqualTo(expected.getDireccion()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getCorreo()).as("check correo").isEqualTo(expected.getCorreo()))
            .satisfies(a -> assertThat(a.getLogo()).as("check logo").isEqualTo(expected.getLogo()))
            .satisfies(a -> assertThat(a.getLogoContentType()).as("check logo contenty type").isEqualTo(expected.getLogoContentType()))
            .satisfies(a -> assertThat(a.getEslogan()).as("check eslogan").isEqualTo(expected.getEslogan()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpresaUpdatableRelationshipsEquals(Empresa expected, Empresa actual) {
        // empty method
    }
}
