package com.ferronica.app.domain;

import static com.ferronica.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class HistorialPrecioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorialPrecioAllPropertiesEquals(HistorialPrecio expected, HistorialPrecio actual) {
        assertHistorialPrecioAutoGeneratedPropertiesEquals(expected, actual);
        assertHistorialPrecioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorialPrecioAllUpdatablePropertiesEquals(HistorialPrecio expected, HistorialPrecio actual) {
        assertHistorialPrecioUpdatableFieldsEquals(expected, actual);
        assertHistorialPrecioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorialPrecioAutoGeneratedPropertiesEquals(HistorialPrecio expected, HistorialPrecio actual) {
        assertThat(actual)
            .as("Verify HistorialPrecio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorialPrecioUpdatableFieldsEquals(HistorialPrecio expected, HistorialPrecio actual) {
        assertThat(actual)
            .as("Verify HistorialPrecio relevant properties")
            .satisfies(a ->
                assertThat(a.getPrecioAnterior())
                    .as("check precioAnterior")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioAnterior())
            )
            .satisfies(a ->
                assertThat(a.getPrecioNuevo())
                    .as("check precioNuevo")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioNuevo())
            )
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
            .satisfies(a -> assertThat(a.getMotivo()).as("check motivo").isEqualTo(expected.getMotivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorialPrecioUpdatableRelationshipsEquals(HistorialPrecio expected, HistorialPrecio actual) {
        assertThat(actual)
            .as("Verify HistorialPrecio relationships")
            .satisfies(a -> assertThat(a.getArticulo()).as("check articulo").isEqualTo(expected.getArticulo()));
    }
}
