package com.ferronica.app.domain;

import static com.ferronica.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class IngresoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngresoAllPropertiesEquals(Ingreso expected, Ingreso actual) {
        assertIngresoAutoGeneratedPropertiesEquals(expected, actual);
        assertIngresoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngresoAllUpdatablePropertiesEquals(Ingreso expected, Ingreso actual) {
        assertIngresoUpdatableFieldsEquals(expected, actual);
        assertIngresoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngresoAutoGeneratedPropertiesEquals(Ingreso expected, Ingreso actual) {
        assertThat(actual)
            .as("Verify Ingreso auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngresoUpdatableFieldsEquals(Ingreso expected, Ingreso actual) {
        assertThat(actual)
            .as("Verify Ingreso relevant properties")
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
            .satisfies(a -> assertThat(a.getNoDocumento()).as("check noDocumento").isEqualTo(expected.getNoDocumento()))
            .satisfies(a -> assertThat(a.getTotal()).as("check total").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotal()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngresoUpdatableRelationshipsEquals(Ingreso expected, Ingreso actual) {
        assertThat(actual)
            .as("Verify Ingreso relationships")
            .satisfies(a -> assertThat(a.getVendedor()).as("check vendedor").isEqualTo(expected.getVendedor()))
            .satisfies(a -> assertThat(a.getProveedor()).as("check proveedor").isEqualTo(expected.getProveedor()));
    }
}
