package com.ferronica.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NumeracionFacturaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNumeracionFacturaAllPropertiesEquals(NumeracionFactura expected, NumeracionFactura actual) {
        assertNumeracionFacturaAutoGeneratedPropertiesEquals(expected, actual);
        assertNumeracionFacturaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNumeracionFacturaAllUpdatablePropertiesEquals(NumeracionFactura expected, NumeracionFactura actual) {
        assertNumeracionFacturaUpdatableFieldsEquals(expected, actual);
        assertNumeracionFacturaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNumeracionFacturaAutoGeneratedPropertiesEquals(NumeracionFactura expected, NumeracionFactura actual) {
        assertThat(actual)
            .as("Verify NumeracionFactura auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNumeracionFacturaUpdatableFieldsEquals(NumeracionFactura expected, NumeracionFactura actual) {
        assertThat(actual)
            .as("Verify NumeracionFactura relevant properties")
            .satisfies(a -> assertThat(a.getSerie()).as("check serie").isEqualTo(expected.getSerie()))
            .satisfies(a -> assertThat(a.getCorrelativoActual()).as("check correlativoActual").isEqualTo(expected.getCorrelativoActual()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNumeracionFacturaUpdatableRelationshipsEquals(NumeracionFactura expected, NumeracionFactura actual) {
        // empty method
    }
}
