package com.ferronica.app.domain;

import static com.ferronica.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class VentaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaAllPropertiesEquals(Venta expected, Venta actual) {
        assertVentaAutoGeneratedPropertiesEquals(expected, actual);
        assertVentaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaAllUpdatablePropertiesEquals(Venta expected, Venta actual) {
        assertVentaUpdatableFieldsEquals(expected, actual);
        assertVentaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaAutoGeneratedPropertiesEquals(Venta expected, Venta actual) {
        assertThat(actual)
            .as("Verify Venta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaUpdatableFieldsEquals(Venta expected, Venta actual) {
        assertThat(actual)
            .as("Verify Venta relevant properties")
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
            .satisfies(a -> assertThat(a.getNoFactura()).as("check noFactura").isEqualTo(expected.getNoFactura()))
            .satisfies(a ->
                assertThat(a.getSubtotal()).as("check subtotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSubtotal())
            )
            .satisfies(a -> assertThat(a.getIva()).as("check iva").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getIva()))
            .satisfies(a -> assertThat(a.getTotal()).as("check total").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotal()))
            .satisfies(a ->
                assertThat(a.getTotalEnMonedaBase())
                    .as("check totalEnMonedaBase")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalEnMonedaBase())
            )
            .satisfies(a -> assertThat(a.getMetodoPago()).as("check metodoPago").isEqualTo(expected.getMetodoPago()))
            .satisfies(a -> assertThat(a.getStripeId()).as("check stripeId").isEqualTo(expected.getStripeId()))
            .satisfies(a -> assertThat(a.getEsContado()).as("check esContado").isEqualTo(expected.getEsContado()))
            .satisfies(a ->
                assertThat(a.getTipoCambioVenta())
                    .as("check tipoCambioVenta")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTipoCambioVenta())
            )
            .satisfies(a -> assertThat(a.getAnulada()).as("check anulada").isEqualTo(expected.getAnulada()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaUpdatableRelationshipsEquals(Venta expected, Venta actual) {
        assertThat(actual)
            .as("Verify Venta relationships")
            .satisfies(a -> assertThat(a.getCliente()).as("check cliente").isEqualTo(expected.getCliente()))
            .satisfies(a -> assertThat(a.getVendedor()).as("check vendedor").isEqualTo(expected.getVendedor()))
            .satisfies(a -> assertThat(a.getMoneda()).as("check moneda").isEqualTo(expected.getMoneda()))
            .satisfies(a -> assertThat(a.getNumeracion()).as("check numeracion").isEqualTo(expected.getNumeracion()));
    }
}
